version: '3.8'

services:
  web:
    build: .
    container_name: background-api
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - shared-net

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-net

volumes:
  postgres_data:

networks:
  shared-net:
    external: true
    name: deep-audio-network