import uuid
from datetime import datetime

from sqlalchemy import Boolean, JSON, String, Text, DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base


class Story(Base):
    """Completed story table.

    Stores the final output of the story generation pipeline.
    In-progress state is tracked separately in StoryDraft; once
    generation is complete the draft is deleted and this record
    holds the permanent data.

    Attributes:
        id: Story ID (UUID).
        child_id: Child ID (FK → children.id).
        theme: Story theme.
        title: Generated title.
        abstracts: All abstract candidates generated by the LLM.
        abstract: The abstract selected by the user.
        content: Generated story body.
        audio_url: URL of the audio file.
        is_deleted: Soft-delete flag.
        created_at: Creation timestamp.
        updated_at: Last updated timestamp.
    """

    __tablename__ = "stories"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    child_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("children.id"), nullable=False, index=True
    )
    theme: Mapped[str] = mapped_column(String, nullable=False)
    title: Mapped[str | None] = mapped_column(String, nullable=True)
    abstracts: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    story_prompts: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    abstract: Mapped[str | None] = mapped_column(Text, nullable=True)
    story_prompt: Mapped[str | None] = mapped_column(Text, nullable=True)
    content: Mapped[str | None] = mapped_column(Text, nullable=True)
    audio_url: Mapped[str | None] = mapped_column(String, nullable=True)
    is_deleted: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    child: Mapped["Child"] = relationship("Child", back_populates="stories")  # noqa: F821
